### ISSUE TITLE
 caused by: UndefVarError: Csigned char not defined

### ISSUE THREAD

**Issue by Moelf** [JuliaHEP/UnROOT.jl#145]
what the heck is signed char...

**Comment by tamasgal** [comment]
Can you provide a little bit more information? 😆

**Comment by Moelf** [comment]
https://github.com/tamasgal/UnROOT.jl/blob/master/src/root.jl#L366-L367

need two new lines:
```
                elseif elname == "signed char" 
                    Int8
```

leaving this open since we could also use a test file

**Comment by tamasgal** [comment]
OK I see ;) Do you happen to have such a small sample file or should we produce one with a Python script?

**Comment by Moelf** [comment]
let's add to one of the python script
