### ISSUE TITLE
[Feature] A branch renaming function?

### ISSUE THREAD

**Issue by Moelf** [JuliaHEP/UnROOT.jl#146]
`Symbol("STDMTruthTausAuxDyn.classifierParticleOrigin")` is crazy branch name and it includes a dot...

**Comment by aminnj** [comment]
Ttrees have a SetAlias function that lets it map a convenient alias to a branch expression and I think these are stored in fAliases. I agree this could be nice. Especially a lazy expression evaluator :) like a pt column lazily constructed from px py columns on the fly.

**Comment by Moelf** [comment]
one thing I want is `normalizenames` like in CSV.jl, which would convert dot to `_`. As for renaming, DataFrames.jl uses `rename!()`

**Comment by Moelf** [comment]
implemented in #225 with a slightly different interface (rename at creation time)
