### ISSUE TITLE
Version selection in documentation is missing

### ISSUE THREAD

**Issue by tamasgal** [JuliaHEP/UnROOT.jl#212]
I stumble upon this over and over and never have time to fix it immediately and then forget about it 😆 So let me create an issue, maybe someone has time to quickly skim over it. It should be easy (but I am in hurry again).

The version selection (bottom left corner of the docs) is stopped working after v0.1: https://juliahep.github.io/UnROOT.jl/dev/

**Comment by Moelf** [comment]
fixed by #213
