### ISSUE TITLE
"Collection is empty" when opening a file found in the wild

### ISSUE THREAD

**Issue by tamasgal** [JuliaHEP/UnROOT.jl#215]
UnROOT fails to open a file which I found by accident in https://github.com/scikit-hep/uproot5/discussions/823

I have not looked into it yet but I'll file it as an issue since the opening of files and simple browsing should be possible. It seems to be related to `MMapStream`, but we'll see...

```
julia> f = UnROOT.ROOTFile("/Users/tamasgal/Downloads/output.root")
ROOTFile with 8 entries and 34 streamers.
/Users/tamasgal/Downloads/output.root
Error showing value of type ROOTFile:
ERROR: ArgumentError: Collection is empty, must contain exactly 1 element
Stacktrace:
  [1] only
    @ ./iterators.jl:1408 [inlined]
  [2] read(fobj::UnROOT.MmapStream, #unused#::Type{UInt8})
    @ UnROOT ~/Dev/UnROOT.jl/src/streamsource.jl:88
  [3] readtype
    @ ~/Dev/UnROOT.jl/src/io.jl:23 [inlined]
  [4] readtype(io::UnROOT.MmapStream, #unused#::Type{String})
    @ UnROOT ~/Dev/UnROOT.jl/src/io.jl:30
  [5] unpack(io::UnROOT.MmapStream, #unused#::Type{UnROOT.TKey64})
    @ UnROOT ~/Dev/UnROOT.jl/src/io.jl:75
  [6] unpack
```

[output.zip](https://github.com/JuliaHEP/UnROOT.jl/files/10730416/output.zip)

**Comment by Moelf** [comment]
Uproot can't handle it either, and when opening with ROOT I see weird warning and can't get Scan to work.

idk, maybe "Won't fix" ?

**Comment by tamasgal** [comment]
Ah ok, then let's add a wontfix and at least there is something for the full-text-search in future.
