### ISSUE TITLE
`lazytree` that takes either a file or a directory full of similar files

### ISSUE THREAD

**Issue by Yuan-Ru-Lin** [JuliaHEP/UnROOT.jl#224]
I propose a common API for creating a `LazyTree` from either a file and a directory full of similar files.

The implementation is quite simple:

```julia
using UnROOT

function lazytree(path::AbstractString, key::AbstractString)
    if isfile(path)
        LazyTree(path, key)
    elseif isdir(path)
        UnROOT.chaintrees(LazyTree(_path, key) for _path in readdir(path, join=true))
    else
        error("wrong path")
    end
end
```

Here is a demo:

```julia
julia> ;
shell> tree
.
├── file.root
└── dir
    ├── file1.root
    └── file2.root

1 directories, 3 files

shell>
julia> lazytree("file.root", "tree")  # will work
...
julia> lazytree("dir", "tree")  # will work
...
julia> lazytree("nonnexistent", "tree")  # will error
```

**Comment by Moelf** [comment]
Because user can easily do this, we should leave it to the user, particularly, there's no guarantee when `path` is a directory, all files in that directory are `.root` files.

**Comment by Yuan-Ru-Lin** [comment]
> there's no guarantee when path is a directory, all files in that directory are .root files.

Good point. Let me close this then.
