### ISSUE TITLE
xrootdgo exits the Julia session if the URL is not accessible

### ISSUE THREAD

**Issue by tamasgal** [JuliaHEP/UnROOT.jl#228]
I am currently unable to run the tests of UnROOT because `xrootdgo.Open` hangs and crashes Julia completely if the stream is not available:

```
julia> r = ROOTFile("root://eospublic.cern.ch//eos/root-eos/cms_opendata_2012_nanoaod/Run2012B_DoubleMuParked.root")
(baseurl, filepath) = ("eospublic.cern.ch", "/eos/root-eos/cms_opendata_2012_nanoaod/Run2012B_DoubleMuParked.root")
2023/03/15 14:05:14 invalid argument

░ tamasgal@silentbox:UnROOT.jl  master $●● ஃ v1.8.5 took 3m 8s 
░ 14:05:14 1 > 
```

I think this needs to be fixed upstream since we can't catch this error.

**Comment by tamasgal** [comment]
Yep, good idea!

**Comment by tamasgal** [comment]
Btw. since it's working in the CI, I assume it's related to the networking/firewall here (I am currently at the GSI in Germany/Darmstadt and the guest WiFi might be a bit too restrictive).

Adding a timeout via a macro would work, at least for the test suite, something like this: https://discourse.julialang.org/t/help-writing-a-timeout-macro/16591/6?u=tamasgal

but in the long-term, it would be good if we could catch an error.

**Comment by sbinet** [comment]
what is the exact GoHEP code being called ? (and do you have a reproducer ?)

**Comment by Moelf** [comment]
@sbinet thanks for the rely,

https://github.com/JuliaPackaging/Yggdrasil/blob/994449f4c6563f437ec13e5e48f15ab2b5740fdb/X/xrootdgo/bundled/main.go#L18-L27

upon looking at this, maybe the `Fatal()` can be changed into a non-exit behavior?

**Comment by sbinet** [comment]
Yes the issue is your call to Fatal.
You should handle the error with whatever mechanism integrates best with the C FFI of Julia.

(Fatal is eventually calling exit(1))

-s
