### ISSUE TITLE
Type stability regression introduced in 0.10.6

### ISSUE THREAD

**Issue by Moelf** [JuliaHEP/UnROOT.jl#242]
https://github.com/JuliaHEP/UnROOT.jl/compare/v0.10.4...v0.10.6

```julia
# setup.jl
using UnROOT

struct TheTree{T}
    _fobj::UnROOT.ROOTFile
    _t::T

    function TheTree(fobj::UnROOT.ROOTFile)
        tree = LazyTree(fobj, "E", ["Evt/mc_hits/mc_hits.id"])
        new{typeof(tree)}(fobj, tree)
    end
end

struct TheFile{T}
    _fobj::UnROOT.ROOTFile
    tree::T

    function TheFile(filename::AbstractString)
        fobj = ROOTFile(filename)
        tree = TheTree(fobj)
        new{typeof(tree)}(fobj, tree)
    end
end

function Base.getindex(tree::TheTree{T}, idx::Integer) where T
    e = tree._t[idx]
    length(e.Evt_mc_hits_mc_hits_id)
end
```

then
```julia
julia> includet("setup.jl")
[ Info: Precompiling UnROOT [3cd96dde-e98d-4713-81e9-a4a1b0235ce9]

julia> const f = TheFile(UnROOT.samplefile("km3net_offline.root").filename);

julia> @code_warntype f.tree[1]
```

**Comment by Moelf** [comment]
@tamasgal

**Comment by Moelf** [comment]
when we fix this we should add a test

**Comment by tamasgal** [comment]
Thanks for hunting this down 😉

**Comment by tamasgal** [comment]
My best guess currently is

https://github.com/JuliaHEP/UnROOT.jl/compare/v0.10.5...v0.10.6#diff-96fd19227b50278b8b930998f46f92b76e3d9524a81988f16c6d47fbe7b99d6fR60

I'm having a look...

**Comment by tamasgal** [comment]
And this line:

https://github.com/JuliaHEP/UnROOT.jl/compare/v0.10.5...v0.10.6#diff-96fd19227b50278b8b930998f46f92b76e3d9524a81988f16c6d47fbe7b99d6fR193

So in principle, we have a type inference problem because `.fBasketEntry` and `.fBaskets.elements` are not type-safe.

**Comment by tamasgal** [comment]
Actually I think we are rather dancing at the edge of type interference nesting and a single line where we check if `findfirst` returns `nothing` totally breaks the inference.

Look at this rewritten `_localindex_newbasket!()` function which now dispatches on two different `_get_buffer_range()` functions. The one which dispatches on `Nothing` is commented out. Everything works. If I comment it back, it's unstable again:

```julia
function _localindex_newbasket!(ba::LazyBranch{T,J,B}, idx::Integer, tid::Int) where {T,J,B}
    seek_idx = findfirst(x -> x > (idx - 1), ba.fEntry) #support 1.0 syntax
    br = _get_buffer_range(ba, tid, seek_idx)
    ba.buffer_range[tid] = br
    return idx - br.start + 1
end

function _get_buffer_range(ba::LazyBranch{T, J, B}, tid::Integer, seek_idx::Integer) where {T,J,B}
    seek_idx -= 1
    ba.buffer[tid] = basketarray(ba.f, ba.b, seek_idx)
    (ba.fEntry[seek_idx] + 1):(ba.fEntry[seek_idx + 1])
end

# function _get_buffer_range(ba::LazyBranch{T, J, B}, tid::Integer, ::Nothing) where {T,J,B}
#     ba.buffer[tid] = basketarray(ba.f, ba.b, -1)  # -1 indicating recovered basket mechanics
#     # FIXME: this range is probably wrong for jagged data with non-empty offsets
#     ba.b.fBasketEntry[end] + 1:ba.b.fEntries
# end
```

The `.fBasketEntry` cannot be the culprit, it's an `Array{Float64}`.

**Comment by tamasgal** [comment]
OK, forcing the return type of the `_get_buffer_range` to be a `UnitRange{Int64}` does the trick. Unfortunately `.fEntries` can also be a `Float64` in older `TTree` versions...
