### ISSUE TITLE
LRU cache preventing unmapping of ROOT files

### ISSUE THREAD

**Issue by grasph** [JuliaHEP/UnROOT.jl#260]
The LRU caches used for  the `(_)getindex` method `in root.jl` is preventing the unmapping of virtual memory from opened ROOT files, when the file is no more referenced by the user.

## Reproducing the issue

Following code can be used to reproduce the issue,

```julia
using UnROOT

# Set here path to the input file
const fname  = "Run2012BC_DoubleMuParked_Muons.root"

for i in 1:10
    println(i)
    f = ROOTFile(fname)
    t = LazyTree(f, "Events")
    sleep(2)
    f = t = nothing
    GC.gc()
    GC.gc()
    GC.gc()
end

GC.gc()

println("Press enter")
readline()
```

Look for the root file path in `/proc/<pid>/smaps` where pid is the julia process. Assuming it's the only julia process running on the machine, following command can be run:

```
cat /proc/$(pgrep julia | head -n 1)/smaps | grep root\$
```

Symptom: the file appears multiple times

Repeat the test after having removing the two `@memoize` statements from the `root.jl` file **or** after inserting in the test code a `Memoization.empty_cache!(UnROOT._getindex)` statement before the `GC.gc()` calls.

In both case the mapping will appear at maximum twice in  `smaps` in the course of the code execution showing the effectiveness of the unmapping during  garbage collection.

## Fix suggestion

Use directly LRUCache w/o the help of `@memoize` and make the caches member of the `ROOTFile` and `ROOTDirectory`  structs.  That way the memory addresses will be unmapped by the garbage collection of the ROOTFile and ROOTDirectory instances.

**Comment by Moelf** [comment]
Nice finding, I think basically the memorized function shouldn't take ROOTFile as input argument because that makes the key lingers in LRU cache.


But this shouldn't be a problem other than producing bigger mapping number right? Since we only MMap the file, it's technically not real memory used

**Comment by grasph** [comment]
Moelf wrote: "But this shouldn't be a problem other than producing bigger mapping number right? Since we only MMap the file, it's technically not real memory used."

It uses virtual memory address space. This address space is quite large on 64-bit architecture and much more limited on 32-bit one. It's any case a good practice to release resource, when no more needed.

I've also observed that it increases the resident set size (RSS). I expect it's an artifact, because in my test it went  well beyond the physical memory with no impact on performance. Nevertheless, it can be worrying for the user and can be a real problem if a limit is set on RSS usage (see ulimit). My linux kernel version is 5.10.0.

My guess is that file data loaded by the kernel  in the memory buffer are counted, even they have been discarded and until the memory is unmapped. 

Philippe.

**Comment by tamasgal** [comment]
Thanks for the investigation and fix proposal Philippe!

I have not have time to reproduce the issue yet but was wondering if closing the file properly (which is also a good practice `;)`) in your example would make any difference.

**Comment by grasph** [comment]
It doesn't change. You need the ROOTFile instance and its fobj to be garbage collected, which was prevented by the reference in the LRU cache.

**Comment by tamasgal** [comment]
Yes, you are right!

I think https://github.com/JuliaHEP/UnROOT.jl/pull/261 should work, but have not verified yet.

**Comment by Moelf** [comment]
That PR also has tests

**Comment by tamasgal** [comment]
Yep, saw them already. We can merge if you agree :)
