### ISSUE TITLE
Pre-compilation failure after upgrading to v1.9.3

### ISSUE THREAD

**Issue by Yuan-Ru-Lin** [JuliaHEP/UnROOT.jl#271]
I upgraded to v1.9.3 and couldn't compile the package.

```julia 
  _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.3 (2023-08-24)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using UnROOT
[ Info: Precompiling UnROOT [3cd96dde-e98d-4713-81e9-a4a1b0235ce9]
/global/u2/y/yuanru/.julia/juliaup/julia-1.9.3+0.x64.linux.gnu/bin/julia: symbol lookup error: /global/homes/y/yuanru/.julia/artifacts/c51d09a2e5bd45ce61b06c5aab04d9e8087b8f8e/lib/libssl.so: undefined symbol: EVP_idea_cbc, version OPENSSL_1_1_0
ERROR: Failed to precompile UnROOT [3cd96dde-e98d-4713-81e9-a4a1b0235ce9] to "/global/homes/y/yuanru/.julia/compiled/v1.9/UnROOT/jl_JPW92r".
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
   @ Base ./loading.jl:2300
 [3] compilecache
   @ ./loading.jl:2167 [inlined]
 [4] _require(pkg::Base.PkgId, env::String)
   @ Base ./loading.jl:1805
 [5] _require_prelocked(uuidkey::Base.PkgId, env::String)
   @ Base ./loading.jl:1660
 [6] macro expansion
   @ ./loading.jl:1648 [inlined]
 [7] macro expansion
   @ ./lock.jl:267 [inlined]
 [8] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:1611
```

**Comment by Yuan-Ru-Lin** [comment]
> upgrade to 0.10.15 for UnROOT, and potentially nuke your ~/.julia/compiled folder

Neither of them worked, but adding the library path to `LD_LIBRARY_PATH` serves as a workaround.

**Comment by Yuan-Ru-Lin** [comment]
[There](https://github.com/JuliaWeb/OpenSSL.jl/issues/13) is a related issue in OpenSSL.jl, but it suggests add a downgraded version of the package as a dependency to match the version that the system is using, but that constraints lots of other packages' versions. I guess I'll just stay with the `LD_LIBRARY_PATH` workaround.

Since this is not really related to UnROOT, I guess we can close the issue as not planned. What do you say? @Moelf

**Comment by Moelf** [comment]
we can, but I'm also happy to learn more about what happened.

Is it failing due to the `HTTP`-source precompilation in UnROOT.jl itself? and also, are you setting up your environment via things like `cvmfs`

**Comment by tamasgal** [comment]
This might also be insightful: https://discourse.julialang.org/t/forward-compatibility-and-stability-of-julia-vs-packages/97968/50?u=tamasgal
