### ISSUE TITLE
Performance for trees with a large number of branches

### ISSUE THREAD

**Issue by grasph** [JuliaHEP/UnROOT.jl#272]
Performance for trees with large number of branches

Instantiating a `LazyTree` for a CMS nanoaod takes 20 seconds with v0.10.15,
which I expect too large for a good user experience. Below, the comparison with
`RDataFrame` used from ROOT REPL:

| Operation                  | Interpreted ROOT</br> TTree | ROOT</br> RDataFrame | UnROOT</br>  v0.10.15 | UnROOT</br> v0.10.16   |
|----------------------------|------------------|-------------------|----------|----------|
| Setup time [s]             |             0.10 |             0.003 |      21. | 115      |
| First-processing time [s]  |              2.9 |              0.08 |     0.21 |  0.25    |
| Second-processing time [s] |              2.9 |             0.004 |   0.0015 | 0.0015   |

The setup time corresponds to instantiating the `RDataFrame` or `LazyTree`, including file opening.

The first processing computes the sum of muons over all the events, the second
does the same for jets. The difference is due to the time of compilation happening at the first processing.

v0.10.16 is affected by an extra issue for the setup time already reported in PR#.

The Tree contains many branches (1689). The setup time increases non linearly
with the number of branches: it takes 1.9s if only 706 branches are included,
2.8s if only the other 983 branches are included, while as quoted in the table,
it takes 21s for the 706+983=1689 branches.

Note that the LazyTree memory footprint (from Base.summarysize()) is similar to
the file size: are the compressed baskets loaded in memory?

For v0.10.16, the footprint is 220 times the file size.

Testing code:
```julia
using UnROOT

@time l2 = LazyTree("nanoaod.root", "Events");
@time sum(l2.nMuon)
@time sum(l2.nJet)
println("Lazy Tree memory footprint: ", Base.summarysize(l2) , " bytes")
```

**Comment by Moelf** [comment]
yep, I have know about this for a while now... 
- https://github.com/JuliaHEP/UnROOT.jl/issues/269

sorry, I'm pretty sure it was introduced in:
- https://github.com/JuliaHEP/UnROOT.jl/commit/d61fe1af0bd5802e736186849bc1c64ee7bec0fb

because we lost cache :(  will try to fix this soon

**Comment by Moelf** [comment]
on a separate note:

>The Tree contains many branches (1689). The setup time increases non linearly
with the number of branches: it takes 1.9s if only 706 branches are included,
2.8s if only the other 983 branches are included, 

I think this is not surprising because we "abuse" the type system a bit, maybe we should default to DataFrames.jl behavior, and only when user needs `for evt in tree` performance, we let them opt-in to this penalty?

**Comment by grasph** [comment]
Hello Jerry,

I missed to refer to #269 in the post. I've opened a different issue to address improving  performance beyond the pre-v0.10.16 one.

The proposal to default to DataFrame sounds good to me. I like the [CSV.read interface](https://csv.juliadata.org/stable/reading.html#CSV.read) approach to specify the sink.

Philippe.

**Comment by grasph** [comment]
Note that converting the LazyTree to a TypedTables Table takes less than 100ms. So we should be able to have typed column without the large time penalty?

**Comment by Moelf** [comment]
>Note that converting the LazyTree to a TypedTables Table takes less than 100ms. So we should be able to have typed column without the large time penalty?

right now 100ms sounds reasonable to me. But try to see the latency of converting a 1600-column wide `DataFrame` to `TypedTables` for the first time, I suspect it would be kinda slow too.

- - -

We probably want to change the default behavior at 1.0, because this would completely break
```julia
tree = LazyTree(...)

for evt in tree
...
end
```

in terms of performance

**Comment by tamasgal** [comment]
We will do a hackathon at JuliaHEP ;) We have a huge todo list...

**Comment by grasph** [comment]
I expect  for 0.x.y, an option to choose DataFrame and a notice in the documentation is sufficient.

Here is an attempt that adds a sink option to LazyTree: https://github.com/JuliaHEP/UnROOT.jl/compare/master...grasph:UnROOT.jl:sink-option

TBC that it does not break anything and keep row loop performance.

With DataFrame it takes 6.5s instead of the 21s. Not as fast as wished, but it's already an improvement.

Philippe.

**Comment by oschulz** [comment]
DataFrames is a heavy dependency though ...

**Comment by grasph** [comment]
2.5 s after adding copycols=true

**Comment by Moelf** [comment]
using `./test/samples/NanoAODv5_sample.root` we have in the repo, I see

## v0.10.15
```julia
julia> @time LazyTree("./test/samples/NanoAODv5_sample.root", "Events");
  1.158496 seconds (7.63 M allocations: 1.040 GiB, 12.09% gc time, 49.04% compilation time)
```

## master
```julia
julia> @time LazyTree("./test/samples/NanoAODv5_sample.root", "Events");
 67.227559 seconds (466.77 M allocations: 34.525 GiB, 13.13% gc time, 0.75% compilation time)
```

**Comment by Moelf** [comment]
oh, but on v0.10.15

```julia
julia> @time LazyTree("./test/samples/NanoAODv5_sample.root", "Events");
  1.444993 seconds (8.10 M allocations: 1.072 GiB, 7.23% gc time, 69.73% compilation time)

julia> @time LazyTree("./test/samples/NanoAODv5_sample.root", "Events");
ERROR: KeyError: key ((ROOTFile with 1 entry and 18 streamers.
/home/akako/Documents/github/dotFiles/homedir/.julia/dev/UnROOT/test/samples/tree_with_jagged_array.root
, "t1"), ()) not found
Stacktrace:
```

:(
