### ISSUE TITLE
Working with LazyTree as a DataFrame

### ISSUE THREAD

**Issue by peremato** [JuliaHEP/UnROOT.jl#73]
I'm new to Julia wanting to see its potential for HEP computing. For this, I am playing with a TTree with UnROOT to see how this compares with equivalent job with ROOT/RDataFrame. 
I understand that a`LazyTree` is not a `DataFrame`, since in general you cannot not fit in memory the full `TTree`, however it provides the basic functionality of an `AbstractDataFrame`. Naively I thought that I could use initially a `LazyTree` and then once it is heavily reduced to be converted to a `DataFrame`. But this seems not to be working. Perhaps you can give me some hints.
The code I am trying to execute is as follows:
```julia
using UnROOT
f = ROOTFile("/eos/opendata/cms/derived-data/AOD2NanoAODOutreachTool/Run2012BC_DoubleMuParked_Muons.root")
events = LazyTree(f, "Events");
df = filter([:nMuon,:Muon_charge] => (n,c) -> n == 2 && c[1] != c[2], events[1:1000000])
```
and the error I get is:
```
MethodError: no method matching getindex(::LazyTree{TypedTables.Table{NamedTuple{(:Muon_phi, :nMuon, :Muon_pt, :Muon_eta, :Muon_charge, :Muon_mass), Tuple{SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{Int64}}, true}, UInt32, SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{Int64}}, true}, SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{Int64}}, true}, SubArray{Int32, 1, Vector{Int32}, Tuple{UnitRange{Int64}}, true}, SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{Int64}}, true}}}, 1, NamedTuple{(:Muon_phi, :nMuon, :Muon_pt, :Muon_eta, :Muon_charge, :Muon_mass), Tuple{Vector{SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{Int64}}, true}}, Vector{UInt32}, Vector{SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{Int64}}, true}}, Vector{SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{Int64}}, true}}, Vector{SubArray{Int32, 1, Vector{Int32}, Tuple{UnitRange{Int64}}, true}}, Vector{SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{Int64}}, true}}}}}}, ::BitVector, ::Colon)
Closest candidates are:
  getindex(::AbstractDataFrame, ::Integer, ::Colon) at /eos/user/m/mato/.julia/packages/DataFrames/vuMM8/src/dataframerow/dataframerow.jl:210
  getindex(::AbstractDataFrame, ::Integer, ::Union{Colon, Regex, AbstractVector{T} where T, All, Between, Cols, InvertedIndex}) at /eos/user/m/mato/.julia/packages/DataFrames/vuMM8/src/dataframerow/dataframerow.jl:208
  getindex(::AbstractDataFrame, ::CartesianIndex{2}) at /eos/user/m/mato/.julia/packages/DataFrames/vuMM8/src/other/broadcasting.jl:3
  ...

Stacktrace:
 [1] #filter#88
   @ ~.julia/packages/DataFrames/vuMM8/src/abstractdataframe/abstractdataframe.jl:1040 [inlined]
 [2] filter(::Pair{Vector{Symbol}, var"#5#6"}, df::LazyTree{TypedTables.Table{NamedTuple{(:Muon_phi, :nMuon, :Muon_pt, :Muon_eta, :Muon_charge, :Muon_mass), Tuple{SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{Int64}}, true}, UInt32, SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{Int64}}, true}, SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{Int64}}, true}, SubArray{Int32, 1, Vector{Int32}, Tuple{UnitRange{Int64}}, true}, SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{Int64}}, true}}}, 1, NamedTuple{(:Muon_phi, :nMuon, :Muon_pt, :Muon_eta, :Muon_charge, :Muon_mass), Tuple{Vector{SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{Int64}}, true}}, Vector{UInt32}, Vector{SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{Int64}}, true}}, Vector{SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{Int64}}, true}}, Vector{SubArray{Int32, 1, Vector{Int32}, Tuple{UnitRange{Int64}}, true}}, Vector{SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{Int64}}, true}}}}}})
   @ DataFrames ~.julia/packages/DataFrames/vuMM8/src/abstractdataframe/abstractdataframe.jl:1035
 [3] macro expansion
   @ In[5]:3 [inlined]
 [4] top-level scope
   @ timing.jl:210
 [5] eval
   @ ./boot.jl:360 [inlined]
 [6] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1094
``` 

If instead of passing a `LazyTree` I construct a  `DataFrame`, then it works nicely. However it means, I think,  that I have copied in memory the full TTree.
```julia
df = filter([:nMuon,:Muon_charge] => (n,c) -> n == 2 && c[1] != c[2], DataFrame(events[1:1000000]))
```

**Comment by peremato** [comment]
A couple of examples with some complexity using RDataFrame and accessing Open Data. 
https://github.com/cms-opendata-analyses/HiggsTauTauNanoAODOutreachAnalysis
https://root.cern/doc/master/df103__NanoAODHiggsAnalysis_8py.html
It would be nice to compare them with pure Julia equivalent.

**Comment by Moelf** [comment]
Those are way too long and I can't quite figure out where does some functions in string comes from for example `pt_cuts()`.

Is it not possible to have a single-object example?

**Comment by tamasgal** [comment]
Indeed, the pure Julia equivalent would be completely different. In the example above, there are many high-level cuts (btw. the string-evaluation-style coding is really awful for clarity) which do multiple iterations over and over again. In Julia, you'd likely do it straight forward in a simple loop.

Just to show a dumb example; people doing data reduction in Python tend to work with Pandas `DataFrame`s à la:

```python
>>> df = df[df.a < 10]
>>> df = df[np.abs(df.b < 1) & (np.c > 0)]
>>> df = df[df.a + df.b < 0.4]
>>> ...
```

in this example, 10 temporary datasets are created and there are multiple loops over the same elements over and over. Depending on the data size, this can cause enormous memory overhead and heavy calculations lead to wasted CPU resources too.

In Julia you'd most likely iterate once and build up your final dataset element-wise, step-by-step. Clear, concise and with a low memory footprint and efficient CPU usage.

...and the best thing is: you don't have to learn fancy slicing tricks to circumvent the above mentioned issues, you just code your algorithm straight forward.

In my opinion, it would be an easy exercise to work through https://root.cern/doc/master/df103__NanoAODHiggsAnalysis_8py.html and implement it in Julia, but it requires time, which probably should be invested by someone who needs it `;)`

**Comment by peremato** [comment]
> Those are way too long and I can't quite figure out where does some functions in string comes from for example `pt_cuts()` in the second link (`.h` file somewhere?).

The header file is https://github.com/root-project/root/blob/master/tutorials/dataframe/df103_NanoAODHiggsAnalysis_python.h

> Is it not possible to have a single-objective example? Each of them have too many histograms weaved in, making exact comparison will be impossible because too many non-event-loop related cost.

I understand it is quite a lot of work, but comparing the performance, code clarity, debugability, concurrency, etc. of an analysis like this from the ROOT input file to the final set of histograms it is worth to having convincing elements to the HEP community of the advantages of Julia versus C++/Python.

**Comment by peremato** [comment]
> Indeed, the pure Julia equivalent would be completely different. In the example above, there are many high-level cuts (btw. the string-evaluation-style coding is really awful for clarity) which do multiple iterations over and over again. In Julia, you'd likely do it straight forward in a simple loop.

In RDataFrame all the actions (definitions, filters, etc.) are lazy. There is indeed a single event loop over the full analysis. I do agree that the string-evaluation-style coding is really awful for clarity. This is the main reason why Julia could be very attractive is a reasonable performance is preserved.

> Just to show a dumb example; people doing data reduction in Python tend to work with Pandas `DataFrame`s à la:
> 
> ```python
> >>> df = df[df.a < 10]
> >>> df = df[np.abs(df.b < 1) & (np.c > 0)]
> >>> df = df[df.a + df.b < 0.4]
> >>> ...
> ```
> 
> in this example, 10 temporary datasets are created and there are multiple loops over the same elements over and over. Depending on the data size, this can cause enormous memory overhead and heavy calculations lead to wasted CPU resources too.

No, if `df` is a `RDataFrame`, then there is no many loops nor many instantiations of temporary datasets. Single loop and no large temporaries.
  
> In Julia you'd most likely iterate once and build up your final dataset element-wise, step-by-step. Clear, concise and with a low memory footprint and efficient CPU usage.
> ...and the best thing is: you don't have to learn fancy slicing tricks to circumvent the above mentioned issues, you just code your algorithm straight forward.

Yes, this is clear. But what you would like is to be able to partition the loop over many cores, workers, nodes, etc. in a fairly easy or transparent manner. 

> In my opinion, it would be an easy exercise to work through https://root.cern/doc/master/df103__NanoAODHiggsAnalysis_8py.html and implement it in Julia, but it requires time, which probably should be invested by someone who needs it `;)`

I do agree, int requires work and it should be invested somehow.

**Comment by Moelf** [comment]
My fear is that due to the auxiliary code around making plots and histogram and name things, it won't be clear to readers because it's too long to hold in short memory.

To make a constructive example, I think comparing the double loop:
https://root.cern/doc/master/df103__NanoAODHiggsAnalysis__python_8h_source.html#l00026

would be clear. And then compare two filters, and comparing making two histograms. Basically, comparing 20 filters and making 20 histograms doesn't add to the comparison only making examples impossible to comprehend unless users already know Julia

**Comment by tamasgal** [comment]
> No, if df is a RDataFrame, then there is no many loops nor many instantiations of temporary datasets. Single loop and no large temporaries.

Ah OK, sorry for my ignorance. This makes the comparison even more interesting `:)`

**Comment by peremato** [comment]
> To make a constructive example, I think comparing the double loop:
> https://root.cern/doc/master/df103__NanoAODHiggsAnalysis__python_8h_source.html#l00026
> would be clear. And then compare two filters, and comparing making two histograms.

Yes, I do agree it is good to start with.

**Comment by Moelf** [comment]
ok let me try to write a blog-like article and compare a few "kernel" functions like that and build up to a mini full analysis with two cuts and two histograms

**Comment by Moelf** [comment]
I'm writing the said document already and want to put some key observation here for posterity without referring to the full document. This is based on example of: https://root.cern/doc/master/df103__NanoAODHiggsAnalysis_8py_source.html, the function defined on line 145. If you look closely, line 151 and 159 correspond to two functions in: https://root.cern/doc/master/df103__NanoAODHiggsAnalysis__python_8h_source.html header file. In this header file, pay attention to line 41 and line 71.

We see that the invariant mass of the pairs of muons are computed multiple times. This is potentially expensive and we can imagine the same happens for more expensive variables. Now, there's `.Define()`, but it is awkward to use especially your expensive variable is optional and changes from event to event.

You may also think we can merge the two "kernel" functions into one, the problem is that now you need to merge everything in between too, because these two `.Filters()` are not called right after another. => basically you ends up writing a bigger and bigger for loop when you merge kernels for performance reason.

**Comment by peremato** [comment]
I am not sure I am following, although I do see that there is some recalculation that could be perhaps saved between the filtering steps. The `.Define()` adds virtually a new column to the dataframe and works event by event. It is equivalent to declare and set a temporary variable in the event loop, which can be used in a subsequent filter expression. Instead of 'defining' the indices of the leptons to form the Zs you could also return in addition the masses between them. In C++ is not as easy as in Julia and you would need to return a std::pair<>. In my opinion this is not to important here at this stage.

**Comment by Moelf** [comment]
>It is equivalent to declare and set a temporary variable in the event loop, which can be used in a subsequent filter expression

indeed, but consider this pseudo code:
```python
def filter_kernel1():
	calculation...
	if condition1:
		variable1
	else:
		return false
	more_calculation...
	return cond(variable1)
```

and in `filter_kernel2`, depending on if `variable1` exists, you want to re-use it. And there are other `Filters` between these two. Now the difficulty is you need to "break-up" every kernel at places where you have new variables and conditionals (manual SSA?), or, you can write these filters in one function, but only if you also write everything logically between `kernel1` and `kernel2` into the same function as well.

My over all understanding is that, there seem to be not much gain in terms of clarity (string-based, split in C++ and python) and functionality/performance (users still need to know the order of filters, not to repeat calculation and split into `.Define()` for intermediate variables and break up or merge kernel functions accordingly)

**Comment by Moelf** [comment]
btw, since:
https://github.com/JuliaHEP/UnROOT.jl/blob/57e49d3ac52a77174094d1e212b215268a768e8b/src/iteration.jl#LL101-L101C54

converting it to a `DataFrame(; copycols = false)` should just work, we can maybe have integration test one day.
